### ISSUE TITLE
remote image support

### ISSUE THREAD

**Issue by marclundgren** [sindresorhus/wallpaper-cli#2]
I'd love to be able to download and set a remote desktop image.

`wallpaper http://imgur.com/a/DdV4w#VGgJD9O`

**Comment by sindresorhus** [comment]
I don't have time to implement this right now, so PR welcome for anyone wanting this.

Use https://github.com/sindresorhus/is-url-superb to check if it's an URL, then use https://github.com/sindresorhus/got to stream the image into a temp directory (https://github.com/sindresorhus/tempfile), then pass the path to `wallpaper`.
