### ISSUE TITLE
[REJECTED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [sindresorhus/wallpaper-cli#4]
Dear Sindre,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows only?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by SamVerschueren** [comment]
> Works on macOS, Linux, and Windows.

It's a CLI, not a Electron app. Just install with npm and run as documented.

**Comment by sergeevabc** [comment]
@SamVerschueren, I asked about standalone binary explicitly to launch on thumbdrive outside NPM environment hence the subject of issue. Mentioned tools (Nexe, EnclosureJS) state that it’s possible.

**Comment by sindresorhus** [comment]
Feel free to make that. Not something I'm interested in though.

**Comment by SamVerschueren** [comment]
Or the easy way, if `node` is available on every computer you want to use it on. Create a directory `wallpaper` on your thumb drive and `npm install` this package inside that directory. In the root of the directory, create a `.bat` file (or whatever it is called these days) which executes the `node_modules/.bin/wallpaper`. Just an idea though.

**Comment by sergeevabc** [comment]
@sindresorhus, had user been able to polish reported roughness, he would be called a developer…
@SamVerschueren, found a gem by name of [WallpaperChanger][1]: 11 KiB, works flawlessly.

[1]: https://github.com/philhansen/WallpaperChanger

**Comment by SamVerschueren** [comment]
> Had user been able to polish reported roughness, he would be called a developer…

Had open source contributors/maintainers be paid for their work, they would be called employees...

**Comment by sergeevabc** [comment]
@SamVerschueren, the very reason why open source developers are praised is their voluntary alacrity to make life easier. It means doing, even with loose schedules and vague roles, not procrastination, extortion or other passive-aggressive behaviour. Otherwise either project should be honestly marked as abandoned or feedback (i.e. issue tracker) should be muted to strangle public expectations at birth.
