### ISSUE TITLE
When I try to install this module and run wallpaper, I get different output

### ISSUE THREAD

**Issue by Industrial** [sindresorhus/wallpaper-cli#6]
Hi.

I'm getting output for npm 'wallpaper' even though I ran `npm remove -g wallpaper; npm remove -g wallpaper-cli; npm i -g wallpaper-cli; wallpaper --help`;

I'd really like this version since it takes an URL.

**Comment by sindresorhus** [comment]
Maybe you have multiple versions of npm installed, or you changed the npm location without moving the old global node_modules folder. Or you installed it with Yarn. Many reasons this could happen, but not something I can give support for here. This is more of an npm/yarn support question. Try their support channels.
